(docs) updated docs/design.md
cloudposse/geodesic pull request #717
Opened 2021-06-19 03:13 UTC by vladdoster

- update spelling
- update agreement
- correct capitalization
- remove redundancy

2021-06-19 23:03 UTC, Nuru requested changes
Thank you for taking the time and effort to clean up this document. Please accept the few small changes I am requesting and we will be good to go.

2021-06-19 23:03 UTC, Nuru commented on docs/design.md
> +1. Many of our `Makefiles` do an `-include Makefile.*`, which means, we'll include other `Makefiles` in that directory. To add additional functionality, drop in your `Makefile.something` in that dire
```suggestion
1. Many of our `Makefiles` do an `-include Makefile.*`, which means, we'll include other `Makefiles` in that directory. To add additional functionality, simply add a `Makefile.something` file in that directory.
```

2021-06-20 14:19 UTC, vladdoster commented
I'm almost positive the `Labeler / label (pull_request)` failure isn't related to these changes.

Going to cross my i's and cross my t's by squashing these two additional commits.

Thanks for the feedback and review!

2021-06-20 18:40 UTC, Nuru commented
> I'm almost positive the Labeler / label (pull_request) failure isn't related to these changes.

@vladdoster Correct, Labeler simply does not work on forks, because you do not have permission to add labels to this repo. CC: @osterman

2021-06-20 19:09 UTC, Nuru approved these changes

2021-06-20 19:42 UTC, merged