Feat: support tenant label in `eks-update-kubeconfig`
cloudposse/geodesic pull request #734
Opened 2021-09-20 18:14 UTC by korenyoni

## what

* Support optional tenant label in `eks-update-kubeconfig`

## why

* `null-label` supports an optional `tenant` label, however `eks-update-kubeconfig` does not.

## references

- https://github.com/cloudposse/terraform-null-label/releases/tag/0.25.0

## tests

### with tenant label

<details>
<summary>eks-update-kubeconfig mgmt-uw2-sandbox</summary>

```bash
Updated context arn:aws:eks:us-west-2:[REDACTED]:cluster/[REDACTED]-mgmt-uw2-sandbox-eks-cluster in /conf/.kube/kubecfg.mgmt-uw2-sandbox-admin
```
</details>

### without tenant label

<details>
<summary>eks-update-kubeconfig ue1-sandbox</summary>

```bash
Added new context arn:aws:eks:us-east-1:[REDACTED]:cluster/[REDACTED]-ue1-sandbox-eks-cluster to /conf/.kube/kubecfg.ue1-sandbox-admin
```
</details>

2021-09-20 18:19 UTC, nitrocode approved these changes

2021-09-20 18:22 UTC, korenyoni commented
I need to reformat — some tabs / spaces inconsistencies in indentation

2021-09-20 20:23 UTC, osterman commented on rootfs/usr/local/bin/eks-update-kubeconfig
> +  If it is desired to have single kubeconfig file with all contexts, as opposed to a separate kubeconfig file for each
```suggestion
  If it is desired to have a single kubeconfig file with all contexts, as opposed to a separate kubeconfig file for each
```

2021-09-28 06:43 UTC, Nuru requested changes

2021-09-28 06:43 UTC, Nuru commented on rootfs/usr/local/bin/eks-update-kubeconfig
> +
```suggestion
  If you chose to do this, remember that "off" deletes the entire kubeconfig file.
  
```

2021-09-28 06:43 UTC, Nuru commented on rootfs/usr/local/bin/eks-update-kubeconfig
> +	if [[ $1 =~ ^[[:alnum:]]+-[[:alnum:]]+-[[:alnum:]]+$ ]]; then
Although this is probably OK, I prefer the more explicit statement of our convention:
```suggestion
	if [[ $1 =~ ^[^-]+-[^-]+-[^-]+$ ]]; then
```

2021-10-06 13:45 UTC, korenyoni commented
Tested this again in both an environment without a `tenant` label and one with.

2021-11-04 20:45 UTC, korenyoni commented
Updated and tested manually:

<details>
<summary>with atmos < 1.3.4 in environment without the tenant label</summary>

```bash
$ eks-update-kubeconfig ue1-sandbox
WARNING:
The current version of atmos is 0.21.3 (a32a4a4), and the minimum version required to determine if the 'tenant' label
is being used is v1.3.4. Because of this, it is assumed 'tenant' is not used. If you would like to use the 'tenant' label,
update atmos to v1.3.4 or above.

Updated context arn:aws:eks:us-east-1:[REDACTED]:cluster/eg-ue1-sandbox-eks-cluster in /conf/.kube/kubecfg.ue1-sandbox-admin
```

</details>

<details>
<summary>with atmos >= 1.3.4 in environment without the tenant label</summary>

```bash
$ eks-update-kubeconfig ue1-sandbox
Updated context arn:aws:eks:us-east-1:[REDACTED]:cluster/eg-ue1-sandbox-eks-cluster in /conf/.kube/kubecfg.ue1-sandbox-admin
```

</details>

<details>
<summary>with atmos >= 1.3.4 in environment with the tenant label</summary>

```bash
$ eks-update-kubeconfig mgmt-uw2-sandbox
Updated context arn:aws:eks:us-west-2:[REDACTED]:cluster/eg-mgmt-uw2-sandbox-eks-cluster in /conf/.kube/kubecfg.mgmt-uw2-sandbox-admin
```

</details>

2021-11-04 21:21 UTC, Nuru requested changes
Not requesting specific changes, but want to wait for a larger design conversation of which this is just one piece.

2021-11-04 21:21 UTC, Nuru commented on rootfs/usr/local/bin/eks-update-kubeconfig
> +TENANT_LABEL_ENABLED=false
This raises a larger issue of how we support tenants in Geodesic (on the command line/console) versus how we support them via Spacelift. Do we add an environment variable in Dockerfile like we have for `NAMESPACE` and do we add tools for switching tenants along the lines of `assume-role`? We need to have a design sprint for this. @osterman @korenyoni @aknysh @nitrocode

2023-06-29 07:01 UTC, closed without merging